"""check

Revision ID: d954a69f574a
Revises: e09f79e3e087
Create Date: 2019-04-05 12:06:53.465754

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd954a69f574a'
down_revision = 'e09f79e3e087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
